### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by saviornt** [tbienias/PyTwits#1]
When using Google Colaboratory for the development platform, imported the library from pip successfully and imported it into the project. However, when attempting to use the library, it returns:

`---------------------------------------------------------------------------
JSONDecodeError                           Traceback (most recent call last)
<ipython-input-23-02ba7c1b65a5> in <module>()
      1 stocktwits = pt.StockTwits()
----> 2 symbols = stocktwits.search(path='search/symbols', q='AAPL')
      3 aapl = symbols[0]
      4 print("Symbol: {} - Title: {}".format(aapl.symbol, aapl.title))

6 frames
/usr/lib/python3.7/json/decoder.py in raw_decode(self, s, idx)
    353             obj, end = self.scan_once(s, idx)
    354         except StopIteration as err:
--> 355             raise JSONDecodeError("Expecting value", s, err.value) from None
    356         return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

Attempted to use both the .search as well as the .streams function and both returned the same error. For reference, here is the copy/paste code which returned the above error:

```
import pytwits as pt
stocktwits = pt.StockTwits()
symbols = stocktwits.search(path='search/symbols', q='AAPL')
aapl = symbols[0]
print("Symbol: {} - Title: {}".format(aapl.symbol, aapl.title))
```

**Comment by tbienias** [comment]
Your pasted code is working on my end, however I can't provide support for different IDEs etc.
