### ISSUE TITLE
how to get the Token?

### ISSUE THREAD

**Issue by cuevas1208** [tbienias/PyTwits#2]
Need help understanding how the token request process works. I want to submit a post to Stocktwits via python. I understand that I need a token and need to submit criteria to 'https://api.stocktwits.com/api/2/oauth/token' How do I receive and store the token?

**Comment by tbienias** [comment]
Receiving tokens is not implemented and I do not plan to do it.
Workaround for receiving a token is stated here: https://github.com/hamx0r/stocktwits
